---
slug: aquatic-thoughts
filename: aquatic-thoughts
title: Bioluminescence
subtitle: An investigation of the morphology, phylogenetic relationships, and adaptations of various fish taxa that possess photophores. 
description: A review of the literature on bioluminescence in marine fish.
author: Katherine L. Bailey
copyright: 2015
uuid: d871f607-77ad-4af0-bbb8-79948d8754b7
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1

